const jobListings = [
    {
        title: "Content Creator",
        body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo."
    },
    {
        title: "Cloud Design Intern",
        body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo."
    },
    {
        title: "Cyber Security Intern",
        body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo."
    },
    {
        title: "Program Manager",
        body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet suscipit enim, non scelerisque ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sollicitudin odio est, id euismod nunc ornare in. Etiam a arcu eros. Nullam condimentum posuere velit, ut sodales erat tempus eu. Aenean varius in lectus et vestibulum. Donec convallis nisi tortor, id consectetur dolor sodales vitae. Morbi mollis molestie nulla, id interdum sapien laoreet vitae. Vestibulum id tincidunt nibh. Proin quis ultricies libero, non ultricies metus. Vivamus sed magna leo."
    },
]

export default jobListings